# Duke P80 Atlas
structures = { '0': "Total Brain",
               '1': "Cingulum",
               '2': "Midbrain",
               '3': "Substantia nigra",
               '4': "Anterior commissure",
               '5': "Hindbrain",
               '6': "Septum",
               '7': "Diagonal domain",
               '8': "Hypothalamus",
               '9': "Striatum",
              '10': "Diencephalon",
              '11': "Internal Capsule",
              '12': "Hippocampus",
              '13': "Pallidum",
              '14': "Accumbens",
              '15': "Fimbria fornix",
              '16': "Corpus Callosum",
              '17': "Amygdala",
              '18': "Preoptic ares",
              '19': "Isocortex",
              '20': "Cerebellum",
              '21': "Olfactory structures",
              '22': "Bed nuclei stria terminalis",
              '23': "Pituitary",
              '24': "Ventricles",
              '25': "Optic pathway",
              '26': "Pineal gland",
             }